### ISSUE TITLE
Full example with docker compose?

### ISSUE THREAD

**Issue by gionn** [ikinsella/docker-p2pool-vtc#1]
Hi, I was searching a docker solution to run a p2pool node, AFAIK it need a running core to use this image, is it correct?

How are you using it?

I haven't any clues:
```
$ docker run --rm ikinsella/docker-p2pool-vtc
Traceback (most recent call last):
  File "/p2pool-vtc/run_p2pool.py", line 5, in <module>
    main.run()
  File "/p2pool-vtc/p2pool/main.py", line 570, in run
    conf = open(conf_path, 'rb').read()
IOError: [Errno 21] Is a directory: '/data'
```

Thanks.

**Comment by ikinsella** [comment]
Yes, you still need to connect to vertcoind, so I have been launching it alongside a [dockerized vertcoind](https://github.com/lukechilds/docker-vertcoind) instance. The instructions to setup are extremely similar to that repo, so launch it with ```docker run -v /path/to/config/folder:/data -p 9346:9346 -p 9171:9171 ikinsella/docker-p2pool-vtc``` which will expose the correct ports and create a directory ```/data``` in the container with the p2pool config file. I have selected some defaults incase you don't give it a config file, but I HIGHLY recommend you use your own instead.
